remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Up The Stack
description: A Project designed to share content with the Cloud and Cloud-Native Community

google_analytics: [Your Google Analytics tracking ID]

github_username: michaelcade
twitter_username: michaelcade1